pipeline {
    agent { label 'rhel' }

    stages {
        stage('hello') {
            steps {
                script {
                sh "cat /etc/os-release"
                sh "dnf upgrade"
                sh "yum upgrade"
                }
            }
        }
    }
}
