pipeline {
    agent { label 'linux-agent-02-raspberry-pi' }

    stages {
        stage('update_apt') {
            steps {
                sh """

cat /etc/os-release
sudo apt update && sudo apt upgrade -y

"""
            }
        }
    }
}
