pipeline {
    agent { label 'windows-agent-02-work' }

    stages {
        stage('hello') {
            steps {
                script {
                powershell "ls"
                }
            }
        }
    }
}
