pipeline {
    agent { label 'windows' }

    stages {
        stage('hello') {
            steps {
                script {
                pwsh.exe -c "ls"
                }
            }
        }
    }
}
