pipeline {
    agent { label 'pi' }
    stages {
        stage('create_env') {
            steps {
                withGroovy(tool:'3.0.8') {
                sh("""
#                cd /home/ubuntu/git 
                groovy --version             
                groovy execute_shell.groovy
                """)
                }
            }
        }
    }
}
