pipeline {
    agent { label 'pi' }
    stages {
        stage('create_env') {
            steps {
                withGroovy(tool:'3.0.8') {
                sh("""
#                git clone https://github.com/CorbinBlock/jenkins.git
ls
#                 cd jenkins/groovy_plugins_test
                groovy --version             
                groovy execute_shell.groovy
                """)
                }
            }
        }
    }
}
