pipeline {
    agent none
    stages {
        }
        stage('build_work_laptop') {
            agent { 
                label 'windows-02-work'
            }
            steps {
                pwsh("""
                # dbeaver - must install manually to accept prompt
                # winget install 9PNKDR50694P -h #dbeaver
                
                # winget install AdoptOpenJDK.OpenJDK.11 -h
                # winget install Apple.iTunes -h
                # winget install Adobe.Acrobat.Reader.64-bit -h
                # winget install Amazon.AWSCLI -h
                # winget install Cockos.Reaper -h
                # winget install Docker.DockerDesktop -h
                # winget install DominikReichl.KeePass -h
                # winget install Fedora.FedoraMediaWriter -h
                # winget install Git.Git -h
                # winget install Google.Chrome -h
                # winget uninstall 'Azure Data Studio' -h
                # winget install Microsoft.SQLServerManagementStudio -h
                # winget install Microsoft.VisualStudioCode -h
                # winget install Notepad++.Notepad++ -h
                # winget install Python.Python.3 -h
                # winget install RaspberryPiFoundation.RaspberryPiImager -h
                # winget install TheGroovyTeam.Groovy -h
                # winget install Valve.Steam -h
                # winget install WinDirStat -h

                Get-NetIPAddress | Format-Table

                # Install-Module -Force Microsoft.PowerShell.SecretManagement
                # Install-Module -Force Microsoft.PowerShell.SecretStore
                # Install-Module -Force -Name SecretManagement.KeePass -RequiredVersion 0.9.2
            
                New-Item -ItemType Directory -Force -Path /git/docker
                New-Item -ItemType Directory -Force -Path /git/powershell
                New-Item -ItemType Directory -Force -Path /git/python
                
                cd /git
                
                git clone https://github.com/CorbinBlock/docker
                git clone https://github.com/CorbinBlock/powershell
                git clone https://github.com/CorbinBlock/python
    
                bash -c "cd docker; git init; git pull --no-rebase; cd .."
                bash -c "cd powershell; git init; git pull --no-rebase; cd .."
                bash -c "cd python; git init; git pull --no-rebase; cd .."
                
                docker container rm debian_dev_env -f
                # docker builder prune -a -f
                cd docker/debian_dev_env
                ./build_debian_container.ps1; ./run_container.ps1
                docker start debian_dev_env
                ./export_docker_import_wsl.ps1
                # docker volume prune -f
                docker volume ls
                docker container ls
                docker images ls

                """)
            }
        }
    }
}
