pipeline {
    agent none
stages {
        stage('api_set_setup_all') {
            agent { 
                label 'HQDEBASUS01'
            }
            steps {
                sh"""
                sudo su cblock -c " . ~/.profile; api_set_setup_all"
                """
            }
        }    
    }
}
