pipeline {
    agent { label 'windows-agent-02-work' }
    stages {
        stage('create_env') {
            steps {
                withGroovy(tool:'3.0.8') {
                sh("""
                cd /jenkins/workspace/jenkins/powershell_plugin_test/powershell_plugin_test/
                groovy --version             
                groovy execute_shell.groovy
                """)
                }
            }
        }
    }
}
